name: "Solar MQTT Publisher"
description: Publishes solar/grid energy totals to Home Assistant via MQTT Discovery for the Energy Dashboard.
version: "0.1.32"
slug: solar_mqtt_publisher
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://github.com/sujithq/solar-mqtt-publisher
startup: services
boot: auto
stage: stable
panel_icon: mdi:solar-power
services:
  - mqtt:need
timeout: 30
advanced: false
audio: false
video: false
uart: false
gpio: false
host_network: false
apparmor: true
apparmor_profile: hassio-solar_mqtt_publisher
options:
  mqtt:
    host: 127.0.0.1
    password: ""
  api:
    url: "http://host.docker.internal:8080/metrics"
  log:
    level: INFO
schema:
  mqtt:
    host: str
    password: password
  api:
    url: str
  log:
    level: list(TRACE|DEBUG|INFO|WARN|ERROR)